dist: trusty
sudo: required
language: python
matrix:
  include:
  - python: '3.5'
    env: PYTORCH_URL=http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl
before_install:
- sudo apt-get install -qq graphviz
- pip install $PYTORCH_URL
install:
- pip install .
script:
- pytest
deploy:
  - provider: pypi
    user: d.zimmerer
    password:
      secure: YFjzOaYZiFmoW/1yHjLearH7FJ10jdt8q7GJGGYQBiDp3kniC/Ap/wB9AOpKuf3gmTsTU1KSI0pp4SQmEn7oID1JXpHTErFaQewck1wZ9kQ5zjoOKONzZQ/Y3wtGj4m8Grn2sWqxAvmhCpjsz0qSCxZ+QyLh+Ths1VBbXrmnADQitqm3R0J6gHIwedgRp62ensF2WqIs9RWu1dbz2B1FD4KEf+FeWO4i8c+pv3XFcOi9VcYBls0voPBGAMRHSppmUuvghkxu/LrI+SkyaodAPX0GAjWaLeMCqpplKzChkRjKXRQLRwaBCnAxOVeTg70pnYemK6G8G6i6UKsPPXyI92twiP6NRkz4VS4XkvjvBYSeTcukIJlC6ghdPr9G1b8jdLqGI1ZTovkCLrJEdkxk9FCe9AJMxdD727PAwnguFRvwernCFKi/J96ycrcCeRWATdNPZRJWocOSP70xWOsC6/IeCj29eJjEowQhC5HPM4OpBcGjzVzPgBD2U1HFhkLOCqHuTix04XoBGK1Cz128ku0tXQZkjBQ/zYxDR+etPLRK8M0YNLtHJLxnQOOMiWpyEJ+0Asu1sPDrPhmrGCXaMUwbPi8bObIKOjp23LWRGVDnE+rD0diPqHEix9tyaCRqf2DX7ZYbYH6qOpKVmCRZMFyMeKadA3EKwD6i0R7AHEI=
    on:
      tags: true
  - provider: script
    script:
    - |
      cd $TRAVIS_BUILD_DIR
      ls -la
      ./deploy_slim.sh $PYPI_USER $PYPI_PASSWORD
    on:
      branch: trixi-slim-publish
